DEFAULT_HISTORY_LIMIT = 50
DEFAULT_CONTEXT_MESSAGES = 10
DEFAULT_REPLY_CHANCE = 0.10
DEFAULT_COOLDOWN_SECONDS = 300
DEFAULT_MAX_REPLY_SENTENCES = 3
DEFAULT_MODEL_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 256
